version: '3.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: learning-docker
    container_name: learning_app
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - laravel

  #Nginx Service
  webserver:
    image: nginx:alpine 
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "7081:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel
    #MySQL Service
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: learning_docker
      MYSQL_ROOT_PASSWORD: Pss201901
    volumes:
      - ./db:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel
    #PhpMyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - laravel

networks:
  laravel:
